### PR TITLE
Run script enhancements and test directories

### PR DESCRIPTION
**Pull request by ajborla**

### CODE REVIEW

**Comment by ajborla** [comment]
The test scripts (test-*) in each test/ subdirectory appear to suffer permission errors. Each has a file mode of 755 locally, and execute correctly via the 'run-tests.sh' script. Nor sure how I would update them to secure appropriate execution permission.

**Comment by ajborla** [comment]
Also, I don't have Docker installed, so cannot test locally. Maybe it is a commonly-experienced problem ? Open to ideas.

**Comment by ErikSchierboom** [comment]
I think it works for me (apart from me not having installed rexx)

```
erik@schierheim:~/exercism/test-runners/rexx-test-runner/tests/solution-stub-code$ ./test-solution-stub-code 
./runt: line 126: regina: command not found
```

**Comment by ajborla** [comment]
Thanks for your help, Eric. In the end I removed the script call and inlined the test code. Not exactly clean, but workable. I hope to improve things as I become more familiar with Docker.

**Comment by ErikSchierboom** [comment]
Approved. Feel free to merge

**Comment by ajborla** [comment]
Hi Erik,

The PR is still blocked, so I cannot proceed with merging.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
My bad. Should be fine now

**Pull request merged**
